### PR TITLE
SSR fix

### LINKED ISSUE #18: ReferenceError: document is not defined
[The first string](https://github.com/VinceG/vue-click-away/blob/97145ee255f429f87142723c830979ab9d454b99/index.js#L1) is being executed immediately (on script load) and it throws and error on SSR mode:
```
ReferenceError: document is not defined
```

### PR DESCRIPTION
**Pull request by revenkroz**
Fixes: https://github.com/VinceG/vue-click-away/issues/18

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@VinceG any chance we can get this merged and tagged, please?

**Comment by VinceG** [comment]
@jbrooksuk Tagged. @revenkroz Thank You!

**Comment by jbrooksuk** [comment]
Thanks!

**Comment by jbrooksuk** [comment]
Hmm, this doesn't seem to solve it for me:

```
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/james/Code/laravel/forge/node_modules/vue3-click-away/dist/common.js:5:24)
```

**Comment by jbrooksuk** [comment]
Hmm, this doesn't seem to solve it for me:

```
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/james/Code/laravel/forge/node_modules/vue3-click-away/dist/common.js:5:24)

```

**Comment by VinceG** [comment]
@jbrooksuk that was my fault. i just tagged v1.2.4 can you try that.

**Comment by jbrooksuk** [comment]
That's sorted it, thanks!

**Pull request merged**
